"""
Django settings for checklist_service project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import environ
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

DEBUG = True

ALLOWED_HOSTS = [
    "192.168.29.171",
    "https://konstruct.world"
    '192.168.29.168',
    " 192.168.29.239",
    "101.53.133.132",
    "*",
    '192.168.29.239',
    "192.168.1.28",
    "localhost",
    "192.168.29.63",
    "127.0.0.1",
    "192.168.23.214",
    '192.168.16.214',
    '192.168.16.214',
    "192.168.1.12",
    "192.168.1.28",
    '192.168.1.11',
    '192.168.78.214',
    '192.168.78.48']


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'checklists',
    'corsheaders',
    'rest_framework.authtoken',


]


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

SECRET_KEY = env('SECRET_KEY')

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

STATIC_URL = '/static/'
STATICFILES_DIRS = []
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'checklists.authentication.JWTRemoteAuth',
    ],
    # 'DEFAULT_PERMISSION_CLASSES': [
    #     'rest_framework.permissions.IsAuthenticated',
    # ],
}

CORS_ALLOW_ALL_ORIGINS = True  # For development only!
# http://192.168.1.14:8003
local="192.168.29.79"
CORS_ALLOWED_ORIGINS = [
    "http://192.168.78.146:3000",

    # "http://localhost:3000",
    # "http://192.168.1.31:3000",  # Prathamesh
    # "http://192.168.1.5:3000",   # Atharva
    # "http://192.168.1.12:3000",   # vasi
    # "http://192.168.1.23:3000",   # mohit

    # "http://192.168.1.23.214:8001",  # Microservice 1 on your machine
    # "http://192.168.1.23.214:8002",  # Microservice 2 on your machine
    # "http://192.168.1.23.214:8000",  # Microservice 3 on your machine

    "http://192.168.29.239:8000",  # Microservice 1 on your machine
    "http://192.168.29.239:8001",  # Microservice 2 on your machine
    "http://192.168.29.239:8002",

    "http:// 192.168.78.214:3000",
    "http:// 192.168.78.214:3000",

    "http:// 192.168.78.214:8001",
    "http:// 192.168.78.214:8002",
    "http:// 192.168.78.214:8000",

    f"http://{local}:8000",  
    f"http://{local}:8001",  # Microservice 1 on your machine
    f"http://{local}:8002",  # Microservice 1 on your machine
    f"http://{local}:8003",  # Microservice 1 on your machine

    "http://192.168.29.79:8000",  
    "http://192.168.29.79:8001",  # Microservice 1 on your machine
    "http://192.168.29.79:8002",  # Microservice 2 on your machine
    "http://192.168.29.79:8003",
    "http://192.168.29.79:3000",

    "http://192.168.1.31:3000",  # Prathamesh
    "http://192.168.1.11:3000",   # Atharva
    "http://192.168.23.116:3000",   # vasi
    "http://192.168.16.116:3000",   # vasi
    "http://192.168.1.23:3000",   # mohit
    "http://192.168.16.116:3000",
    "http://192.168.1.12:3000",  # Prathamesh
    "http://192.168.16.146:3000",   # stharva
    "http://192.168.16.146:3000",   # stharva
    'http://192.168.16.214:8001',
    'http://192.168.16.214:8000',
    'http://192.168.16.214:8002',
    'http://192.168.16.214:8003',
    "http://192.168.23.214:8001",  # Microservice 1 on your machine
    "http://192.168.23.214:8002",  # Microservice 2 on your machine
    "http://192.168.23.214:8000",  # Microservice 3 on your machine


    "http://101.53.133.132:8001",  # Microservice 1 on your machine
    "http://101.53.133.132:8002",  # Microservice 2 on your machine
    "http://101.53.133.132:3000",
    "http://101.53.133.132:8003",
    "http://101.53.133.132:8000",  # Microservice 3 on your machine
    # Microservice 3 on your machine
    # Microservice 3 on your machine
    "https://konstruct.world",
    'http://127.0.0.1:8001',
    'http://127.0.0.1:8002',
    'http://127.0.0.1:8003',
    'http://127.0.0.1:8000',

]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'checklist_service.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'checklist_service.wsgi.application'

BASE_DIR = Path(__file__).resolve().parent.parent

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
	"timeout": 20,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
