# Generated by Django 5.2.3 on 2025-07-22 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('created_by', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('organization_id', models.IntegerField()),
                ('company_id', models.IntegerField(blank=True, null=True)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(default='project_images/Project.png', upload_to='project_images/')),
                ('created_by', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CategoryLevel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level1', to='projects.category')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryLevel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('category_level1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level2', to='projects.categorylevel1')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryLevel3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('category_level2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level3', to='projects.categorylevel2')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryLevel4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('category_level3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level4', to='projects.categorylevel3')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryLevel5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('category_level4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level5', to='projects.categorylevel4')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryLevel6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('category_level5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level6', to='projects.categorylevel5')),
            ],
        ),
        migrations.CreateModel(
            name='ClientPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('assigned_by', models.IntegerField()),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('delete', models.BooleanField(default=False)),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_purposes', to='projects.allpurpose')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.building')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='building',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purposes', to='projects.clientpurpose')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='projects.project')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='projects.purpose')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.CharField(max_length=200)),
                ('Project', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Flattype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('rooms', models.ManyToManyField(related_name='flattypes', to='projects.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='projects.phase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.purpose')),
            ],
        ),
        migrations.CreateModel(
            name='TransferRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_level', models.BooleanField(default=True)),
                ('room_level', models.BooleanField(default=False)),
                ('checklist_level', models.BooleanField(default=False)),
                ('question_level', models.BooleanField(default=False)),
                ('Zone_level', models.BooleanField(default=False)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_rule', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.building')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.level')),
            ],
        ),
        migrations.CreateModel(
            name='Subzone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subzones', to='projects.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('OCCUPIED', 'Occupied'), ('UNDER_CONSTRUCTION', 'Under Construction'), ('INACTIVE', 'Inactive')], default='PLANNED', max_length=30)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.building')),
                ('flattype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.flattype')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.level')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('subzone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.subzone')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.zone')),
            ],
        ),
    ]
