# Generated by Django 5.2.3 on 2025-08-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purpose',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='purpose',
            unique_together={('project', 'name')},
        ),
        migrations.AddConstraint(
            model_name='purpose',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('project',), name='unique_current_purpose_per_project'),
        ),
    ]
