# Generated by Django 5.2.3 on 2025-08-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_purpose_is_current_alter_purpose_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='sequence',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
