# Generated by Django 5.2.3 on 2025-08-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_phase_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skip_supervisory',
            field=models.BooleanField(default=False),
        ),
    ]
