# Generated by Django 5.2.3 on 2025-08-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_skip_supervisory'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='checklist_repoetory',
            field=models.BooleanField(default=False),
        ),
    ]
