# Generated by Django 5.2.3 on 2025-08-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_checklist_repoetory'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Maker_to_chechker',
            field=models.BooleanField(default=False),
        ),
    ]
