# Generated by Django 5.2.3 on 2025-08-23 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_maker_to_chechker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Maker_to_chechker',
            new_name='maker_to_chechker',
        ),
    ]
