# Generated by Django 5.1.4 on 2025-06-27 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('building_id', models.IntegerField(blank=True, null=True)),
                ('zone_id', models.IntegerField(blank=True, null=True)),
                ('flat_id', models.IntegerField(blank=True, null=True)),
                ('phase_id', models.IntegerField(blank=True, null=True)),
                ('stage_id', models.IntegerField(blank=True, null=True)),
                ('work_type_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('photo_required', models.BooleanField(default=False)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('DONE', 'Done by Maker'), ('VERIFYING', 'Verifying by Checker'), ('COMPLETED', 'Completed'), ('REOPENED', 'Reopened')], default='NOT_STARTED', max_length=20)),
                ('is_done', models.BooleanField(default=False)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklists.checklist')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItemSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_by_id', models.IntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('maker_photo', models.ImageField(blank=True, null=True, upload_to='checklist_item_photos/')),
                ('checker_decision', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('NA', 'Not Applicable')], max_length=10, null=True)),
                ('check_photo', models.ImageField(blank=True, null=True, upload_to='checklist_check_photos/')),
                ('check_remark', models.TextField(blank=True)),
                ('checked_by_id', models.IntegerField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_submissions', to='checklists.checklist')),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='checklists.checklistitem')),
            ],
        ),
    ]
