# Generated by Django 5.2.3 on 2025-06-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='work_type_id',
            new_name='subcategory',
        ),
        migrations.AddField(
            model_name='checklist',
            name='category',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
