# Generated by Django 5.2.3 on 2025-06-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_rename_work_type_id_checklist_subcategory_and_more'), ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitemsubmission',
            name='checklist',
        ),
        migrations.AddField(
            model_name='checklistitemsubmission',
            name='status',
            field=models.CharField(
                choices=[
                    ('NOT_STARTED',
                     'Not Started'),
                    ('IN_PROGRESS',
                     'In Progress'),
                    ('COMPLETED',
                     'Completed')],
                default='IN_PROGRESS',
                max_length=25),
        ),
    ]
