# Generated by Django 5.2.3 on 2025-06-30 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_remove_checklistitemsubmission_checklist_and_more'), ]

    operations = [
        migrations.RenameField(
            model_name='checklistitemsubmission',
            old_name='submitted_at',
            new_name='accepted_at',
        ),
        migrations.RenameField(
            model_name='checklistitemsubmission',
            old_name='submitted_by_id',
            new_name='user',
        ),
    ]
