# Generated by Django 5.2.3 on 2025-07-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists',
         '0005_checklist_category_level1_checklist_category_level2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='name',
            field=models.CharField(
                blank=True,
                default='checklist',
                max_length=100),
        ),
    ]
