# Generated by Django 5.2.3 on 2025-07-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists',
         '0007_remove_checklist_subcategory_checklistitemoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='user',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
