# Generated by Django 5.2.3 on 2025-07-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0008_checklist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='user',
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='user',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
