# Generated by Django 5.2.3 on 2025-07-06 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0009_remove_checklist_user_checklistitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitem',
            name='user',
        ),
    ]
