# Generated by Django 5.2.3 on 2025-07-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0010_remove_checklistitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='category',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checklist',
            name='name',
            field=models.CharField(default='checklist', max_length=100),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='purpose_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
