# Generated by Django 5.2.3 on 2025-07-07 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists',
         '0011_alter_checklist_category_alter_checklist_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitemsubmission',
            name='checker_decision',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='checklists.checklistitemoption'),
        ),
    ]
