# Generated by Django 5.2.3 on 2025-07-07 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0012_alter_checklistitemsubmission_checker_decision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitemsubmission',
            name='checker_decision',
        ),
    ]
