# Generated by Django 5.2.3 on 2025-07-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0013_remove_checklistitemsubmission_checker_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitemsubmission',
            name='status',
            field=models.CharField(
                choices=[
                    ('NOT_STARTED',
                     'Not Started'),
                    ('IN_PROGRESS',
                     'In Progress'),
                    ('COMPLETED',
                     'Completed'),
                    ('REJECTED',
                     'Rejected')],
                default='IN_PROGRESS',
                max_length=25),
        ),
    ]
