# Generated by Django 5.2.3 on 2025-07-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0015_checklistitemsubmission_inspected_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='status',
            field=models.CharField(
                choices=[
                    ('NOT_STARTED',
                     'Not Started'),
                    ('IN_PROGRESS',
                     'In Progress'),
                    ('DONE',
                     'Done by Maker'),
                    ('VERIFIED',
                     'Verified by Checker'),
                    ('REVIEW_REJECTED',
                     'Rejected by Reviewer'),
                    ('COMPLETED',
                     'Completed'),
                    ('REOPENED',
                     'Reopened')],
                default='NOT_STARTED',
                max_length=20),
        ),
    ]
