# Generated by Django 5.2.3 on 2025-07-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0016_alter_checklistitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitemoption', name='value', field=models.CharField(
                choices=[
                    ('P', 'Positive'), ('N', 'Negative')], default='P', max_length=50), ), ]
