# Generated by Django 5.2.3 on 2025-07-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0017_alter_checklistitemoption_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='roles_json',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
