# Generated by Django 5.2.3 on 2025-07-09 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0018_checklist_roles_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist', name='roles_json', ), migrations.CreateModel(
            name='ChecklistAccess', fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('initiators', models.JSONField(
                        blank=True, default=list)), ('makers', models.JSONField(
                            blank=True, default=list)), ('checkers', models.JSONField(
                                blank=True, default=list)), ('supervisors', models.JSONField(
                                    blank=True, default=list)), ('checklist', models.OneToOneField(
                                        on_delete=django.db.models.deletion.CASCADE, related_name='access', to='checklists.checklist')), ], ), ]
