# Generated by Django 5.2.3 on 2025-07-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0019_remove_checklist_roles_json_checklistaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDING_MAKER',
                     'Pending Maker'),
                    ('PENDING_CHECKER',
                     'Pending Checker'),
                    ('PENDING_SUPERVISOR',
                     'Pending Supervisor'),
                    ('COMPLETE',
                     'Complete')],
                default='NOT_STARTED',
                max_length=20),
        ),
        migrations.AlterField(
            model_name='checklistitemsubmission',
            name='status',
            field=models.CharField(
                choices=[
                    ('SUBMITTED',
                     'Submitted'),
                    ('APPROVED',
                     'Approved'),
                    ('REJECTED',
                     'Rejected')],
                default='IN_PROGRESS',
                max_length=25),
        ),
    ]
