# Generated by Django 5.2.3 on 2025-07-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0020_alter_checklistitem_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistaccess',
            name='checkers',
        ),
        migrations.RemoveField(
            model_name='checklistaccess',
            name='initiators',
        ),
        migrations.RemoveField(
            model_name='checklistaccess',
            name='makers',
        ),
        migrations.RemoveField(
            model_name='checklistaccess',
            name='supervisors',
        ),
        migrations.AddField(
            model_name='checklistaccess',
            name='roles',
            field=models.JSONField(default=dict),
        ),
    ]
