# Generated by Django 5.2.3 on 2025-07-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0021_remove_checklistaccess_checkers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitemsubmission',
            name='status',
            field=models.CharField(
                choices=[
                    ('IN_PROGRESS',
                     'In Progress'),
                    ('SUBMITTED',
                     'Submitted'),
                    ('APPROVED',
                     'Approved'),
                    ('REJECTED',
                     'Rejected')],
                default='IN_PROGRESS',
                max_length=25),
        ),
    ]
