# Generated by Django 5.2.3 on 2025-07-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0022_alter_checklistitemsubmission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='status',
            field=models.CharField(
                choices=[
                    ('NOT_STARTED',
                     'Not Started'),
                    ('IN_PROGRESS',
                     'In Progress'),
                    ('DONE',
                     'Done by Maker'),
                    ('VERIFIED',
                     'Verified by Checker'),
                    ('REVIEW_REJECTED',
                     'Rejected by Reviewer'),
                    ('COMPLETED',
                     'Completed'),
                    ('REOPENED',
                     'Reopened')],
                default='NOT_STARTED',
                max_length=20),
        ),
        migrations.AlterField(
            model_name='checklistitemsubmission',
            name='status',
            field=models.CharField(
                choices=[
                    ('NOT_STARTED',
                     'Not Started'),
                    ('IN_PROGRESS',
                     'In Progress'),
                    ('COMPLETED',
                     'Completed'),
                    ('REJECTED',
                     'Rejected')],
                default='IN_PROGRESS',
                max_length=25),
        ),
        migrations.DeleteModel(
            name='ChecklistAccess',
        ),
    ]
