# Generated by Django 5.2.3 on 2025-07-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0024_rename_is_done_checklistitem_ignore_now_and_more'), ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='status',
            field=models.CharField(
                choices=[
                    ('not_started',
                     'Not Started'),
                    ('in_progress',
                     'In Progress'),
                    ('work_in_progress',
                     'Work in Progress'),
                    ('completed',
                     'Completed')],
                default='not_started',
                max_length=20),
        ),
    ]
