# Generated by Django 5.2.3 on 2025-07-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0025_alter_checklist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitemoption', name='choice', field=models.CharField(
                choices=[
                    ('P', 'Positive'), ('N', 'Negative')], max_length=20), ), ]
