# Generated by Django 5.2.3 on 2025-07-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0026_alter_checklistitemoption_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='status',
            field=models.CharField(
                choices=[
                    ('not_started',
                     'Not Started'),
                    ('in_progress',
                     'In Progress'),
                    ('pending_for_maker',
                     'Pending for Maker'),
                    ('pending_for_supervisor',
                     'Pending for Supervisor'),
                    ('pending_for_inspector',
                     'Pending for Inspector'),
                    ('completed',
                     'Completed')],
                default='not_started',
                max_length=30),
        ),
        migrations.AlterField(
            model_name='checklistitemsubmission',
            name='status',
            field=models.CharField(
                choices=[
                    ('created',
                     'Created'),
                    ('pending_supervisor',
                     'Pending Supervisor'),
                    ('completed',
                     'Completed'),
                    ('pending_checker',
                     'Pending Checker'),
                    ('rejected_by_supervisor',
                     'Rejected by Supervisor'),
                    ('rejected_by_checker',
                     'Rejected by Checker')],
                default='created',
                max_length=30),
        ),
    ]
