# Generated by Django 5.2.3 on 2025-07-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0028_checklistitemsubmission_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitemsubmission',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
