# Generated by Django 5.2.3 on 2025-07-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0030_alter_checklistitem_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklistitemsubmission',
            old_name='remarks',
            new_name='checker_remarks',
        ),
        migrations.AddField(
            model_name='checklistitemsubmission',
            name='maker_media',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='maker_media/'),
        ),
        migrations.AddField(
            model_name='checklistitemsubmission',
            name='maker_remarks',
            field=models.TextField(
                blank=True,
                null=True),
        ),
        migrations.AddField(
            model_name='checklistitemsubmission',
            name='supervisor_remarks',
            field=models.TextField(
                blank=True,
                null=True),
        ),
    ]
