# Generated by Django 5.2.3 on 2025-07-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists',
         '0031_rename_remarks_checklistitemsubmission_checker_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitemsubmission',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
