# Generated by Django 5.2.3 on 2025-07-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0032_checklistitemsubmission_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='room_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
