# Generated by Django 5.2.3 on 2025-07-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0033_checklist_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='level_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='subzone_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
