# Generated by Django 5.2.3 on 2025-07-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0034_checklist_level_id_checklist_subzone_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('pending_for_inspector', 'Pending for Inspector'), ('tetmpory_inspctor', 'tetmpory_inspctor'), ('pending_for_maker', 'Pending for Maker'), ('pending_for_supervisor', 'Pending for Supervisor'), ('completed', 'Completed')], default='not_started', max_length=30),
        ),
    ]
