# Generated by Django 5.2.3 on 2025-07-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0036_alter_checklistitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='user_generated_id',
            field=models.IntegerField(blank=True, help_text='User ID from the User microservice who generated this checklist', null=True),
        ),
    ]
