# Generated by Django 5.2.3 on 2025-08-01 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0037_checklist_user_generated_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.IntegerField(blank=True, null=True)),
                ('zone', models.IntegerField(blank=True, null=True)),
                ('flat', models.IntegerField(blank=True, null=True)),
                ('room', models.IntegerField(blank=True, null=True)),
                ('stage', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.IntegerField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('checklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checklists.checklist')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'zone', 'flat', 'room', 'checklist', 'is_current'], name='ix_stage_history_lookup')],
                'unique_together': {('project', 'stage', 'zone', 'flat', 'room', 'checklist')},
            },
        ),
    ]
