# Generated by Django 5.2.3 on 2025-08-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0038_stagehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagehistory',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('move_to_next_stage', 'Move to Next Stage'), ('move_to_next_phase', 'Move to Next Phase'), ('completed', 'Completed')], default='started', max_length=30),
        ),
    ]
