# Generated by Django 5.2.3 on 2025-08-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0039_stagehistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagehistory',
            name='phase_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
