# Generated by Django 5.2.3 on 2025-08-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0040_stagehistory_phase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagehistory',
            name='completed_by_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='stagehistory',
            name='crm_completed_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stagehistory',
            name='crm_completed_by_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='stagehistory',
            name='crm_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stagehistory',
            name='crm_hoto',
            field=models.BooleanField(default=False),
        ),
    ]
