# Generated by Django 5.2.3 on 2025-09-10 07:40

import checklists.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0041_stagehistory_completed_by_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItemSubmissionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=checklists.models.submission_image_upload_to)),
                ('who_did', models.CharField(choices=[('maker', 'Maker'), ('supervisor', 'Supervisor'), ('checker', 'Checker'), ('inspector', 'Inspector')], max_length=20)),
                ('uploaded_by_id', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='checklists.checklistitemsubmission')),
            ],
            options={
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['submission', 'who_did', '-captured_at'], name='ix_subm_img_lookup')],
            },
        ),
    ]
