# Generated by Django 5.2.3 on 2025-06-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_remove_company_address_remove_organization_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entity',
            name='created_by',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
