# Generated by Django 5.2.3 on 2025-07-01 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_organization_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together={('created_by', 'name')},
        ),
    ]
