# Generated by Django 5.2.3 on 2025-07-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccess_category_useraccess_subcatgory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccess',
            name='subcatgory',
        ),
        migrations.AddField(
            model_name='useraccess',
            name='CategoryLevel1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='CategoryLevel2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='CategoryLevel3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='CategoryLevel4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='CategoryLevel5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='CategoryLevel6',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
