# Generated by Django 5.2.3 on 2025-07-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_useraccess_subcatgory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccess',
            old_name='CategoryLevel2',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='useraccess',
            old_name='CategoryLevel3',
            new_name='entity',
        ),
        migrations.RemoveField(
            model_name='useraccess',
            name='CategoryLevel4',
        ),
        migrations.RemoveField(
            model_name='useraccess',
            name='CategoryLevel5',
        ),
        migrations.RemoveField(
            model_name='useraccess',
            name='CategoryLevel6',
        ),
        migrations.AddField(
            model_name='useraccess',
            name='org',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraccess',
            name='project_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
