# Generated by Django 5.2.3 on 2025-07-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccess',
            name='company',
        ),
        migrations.RemoveField(
            model_name='useraccess',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='useraccess',
            name='org',
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='entity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='org',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraccess',
            name='category',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
