# Generated by Django 5.2.3 on 2025-07-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_useraccess_company_remove_useraccess_entity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccess',
            name='CategoryLevel2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='CategoryLevel3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='CategoryLevel4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='CategoryLevel5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='CategoryLevel6',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
