# Generated by Django 5.2.3 on 2025-08-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_created_by_alter_useraccessrole_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccess',
            name='phase_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='purpose_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='stage_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
