# Generated by Django 5.2.3 on 2025-08-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_useraccess_phase_id_useraccess_purpose_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccess',
            name='All_checklist',
            field=models.BooleanField(default=False),
        ),
    ]
