# Generated by Django 5.2.3 on 2025-08-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_useraccess_all_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccess',
            name='all_cat',
            field=models.BooleanField(default=True),
        ),
    ]
