# Generated by Django 5.2.3 on 2025-08-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_useraccess_all_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccess',
            name='all_cat',
            field=models.BooleanField(default=False),
        ),
    ]
