# Generated by Django 5.2.3 on 2025-10-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_useraccess_all_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='useraccessrole',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('INITIALIZER', 'Initializer'), ('SUPERVISOR', 'Supervisor'), ('CHECKER', 'Checker'), ('MAKER', 'Maker')], max_length=50),
        ),
    ]
