# Generated by Django 5.2.3 on 2025-11-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_staffregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffregistration',
            name='project_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='role',
            field=models.CharField(default='Staff', max_length=50),
        ),
    ]
