# Generated by Django 5.2.3 on 2025-11-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_staffregistration_project_id_staffregistration_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffregistration',
            name='role',
            field=models.CharField(max_length=50),
        ),
    ]
