# Generated by Django 5.2.3 on 2025-11-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_staffattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffregistration',
            name='staff_profile',
            field=models.ImageField(blank=True, null=True, upload_to='staff_profiles/'),
        ),
    ]
