# Generated by Django 5.2.3 on 2025-11-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_staffregistration_staff_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffregistration',
            name='staff_profile',
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='staff_images/'),
        ),
        migrations.AlterField(
            model_name='staffregistration',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staffregistration',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='staffregistration',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='staffregistration',
            name='project_id',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
