# Generated by Django 5.2.3 on 2025-11-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_staffregistration_staff_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffregistration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
