# Generated by Django 5.2.3 on 2025-11-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_staffregistration_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffregistration',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='staffregistration',
            name='image',
        ),
        migrations.RemoveField(
            model_name='staffregistration',
            name='password',
        ),
        migrations.RemoveField(
            model_name='staffregistration',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff_profile_photos/'),
        ),
        migrations.AlterField(
            model_name='staffregistration',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='staffregistration',
            name='project_id',
            field=models.CharField(max_length=50),
        ),
    ]
