# Generated by Django 5.2.3 on 2025-11-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_staffregistration_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffregistration',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
