# Generated by Django 5.2.3 on 2025-11-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_staffregistration_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffregistration',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='staffregistration',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff_photos/'),
        ),
    ]
