"""
Django settings for organizationservice project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

DEBUG = False

ALLOWED_HOSTS = ["*",'192.168.29.168','192.168.29.239', "192.168.29.171","192.168.29.63"," 192.168.29.239","192.168.1.28", "localhost", "127.0.0.1","192.168.23.214",'192.168.16.214','192.168.16.214',"192.168.1.28",'192.168.1.11','192.168.78.214']


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    # 'rest_framework',
     'django_extensions',
    'organizations',
    'corsheaders',
]


import os
import environ

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

SECRET_KEY = env('SECRET_KEY')

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') 

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'organizations.authentication.JWTRemoteAuth',
    ],
    # 'DEFAULT_PERMISSION_CLASSES': [
    #     'rest_framework.permissions.IsAuthenticated',
    # ],
}

CORS_ALLOW_ALL_ORIGINS = True  
# local="192.168.1.14"

vielocal="192.168.29.79"

CORS_ALLOWED_ORIGINS = [
        "http://192.168.78.146:3000",
    f"http://{locals}:8000",  
    f"http://{locals}:8001",  # Microservice 1 on your machine
    f"http://{locals}:8002",  # Microservice 1 on your machine
    f"http://{locals}:8003",  # Microservice 1 on your machine

    "http://localhost:3000",    
    "http://192.168.1.31:3000",  # Prathamesh
    "http://192.168.1.5:3000",   # Atharva
    "http://192.168.1.12:3000",   # vasi
    "http://192.168.1.23:3000",   # mohit
    "http://192.168.16.146:3000",   # stharva

    "http://192.168.29.239:8000",  # Microservice 1 on your machine
    "http://192.168.29.239:8001",  # Microservice 2 on your machine
    "http://192.168.29.239:8003",

    "http://192.168.1.28:8001",  # Microservice 1 on your machine
    "http://192.168.1.28:8000",  # Microservice 2 on your machine
    "http://192.168.1.28:8003",  # Microservice 3 on your machine
    "http://192.168.23.116:3000",   # vasi
    "http://192.168.1.23:3000",   # mohit
    "http://192.168.29.79:8000",  
    "http://192.168.29.79:8001",  # Microservice 1 on your machine
    "http://192.168.29.79:8002",  # Microservice 2 on your machine
    "http://192.168.29.79:8003",
    "http://192.168.16.146:3000", 
      "http://192.168.1.11:3000",  # stharva
    

    "http://192.168.16.214:8000",
    "http://192.168.16.116:3000",
    "http://192.168.23.214:8001",  # Microservice 1 on your machine
    "http://192.168.23.214:8000",  # Microservice 2 on your machine
    "http://192.168.23.214:8003",  # Microservice 3 on your machine

    "http:// 192.168.78.214:3000",
    "http:// 192.168.78.214:3000",
    
    "http:// 192.168.78.214:8001",
    "http:// 192.168.78.214:8000",
    "http:// 192.168.78.214:8005",

    "http://192.168.1.28:8001",  # Microservice 1 on your machine
    "http://192.168.1.28:8000",  # Microservice 2 on your machine
    "http://192.168.1.28:8003",
    "http://192.168.1.28:8005",  # Microservice 3 on your machine
    "https://konstruct.world",
  # Microservice 3 on your machine
'http://127.0.0.1:8001',
    'http://127.0.0.1:8002',
    'http://127.0.0.1:8003',
    'http://127.0.0.1:8000',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'organizationservice.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'organizationservice.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

BASE_DIR = Path(__file__).resolve().parent.parent
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs/django.log',
            'formatter': 'verbose',
        },
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['file', 'console'],
        'level': 'INFO',
    },
}
